name: sar_ucl
channels:
    - conda-forge
dependencies:
    - jupyterlab
    - notebook
    - nbconvert
    - ipykernel
    - ipywidgets
    - widgetsnbextension
    - matplotlib
    - pandas
    - scipy
    - python>=3.6
    - gdal>=2.3.0
    - tqdm
    - libgdal>=2.3.0
    - jupyter_contrib_nbextensions
    - widgetsnbextension
    - pip
